# dubbo 服务端启用开关
dubbo.server.bootstrap: true
# dubbo 服务端需要暴露的服务接口所在的包
dubbo.servicePackages: com.alibaba.dubbo.demo.service
#
dubbo.application.name: dubbo-demo-provider
# dubbo 服务注册中心配置
dubbo.registry.address: zookeeper://127.0.0.1:2181
#dubbo.registry.address=multicast://224.5.6.7:1234
#dubbo.registry.address=redis://127.0.0.1:6379
#dubbo.registry.address=dubbo://127.0.0.1:9090
# dubbo 协议配置
dubbo.protocol.name: dubbo
dubbo.protocol.port: 20880